services:
  identigraf-uploader:
    build:
      context: .docker/identigraf-uploader
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - NO_UPDATE_NOTIFIER=true
      - NPM_CONFIG_FUND=0
      - SUPPRESS_SUPPORT=1
      - HTTPS=0
      - PORT=3000
      - ENABLE_TRACING=1
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - IDENTIGRAF_UPLOAD_FOLDER=/var/lib/identigraf-uploader/uploads
      - IDENTIGRAF_MAX_FILE_SIZE=5242880
      - HAVE_SWAGGER=true
      - npm_config_userconfig=/usr/src/service/.npmrc.local
    restart: always
    volumes:
      - "../:/usr/src/service"
      - uploads:/var/lib/identigraf-uploader/uploads
    working_dir: /usr/src/service

  zipkin:
    image: openzipkin/zipkin:latest@sha256:c1b981074d5ac8c6d86bd0ee554a00ff8541453ab7fd9d0604a637d1e47db3d9
    restart: always

  swagger:
    image: swaggerapi/swagger-ui:latest@sha256:7e8a319e7f6e96b2328e7a244a0428e92e7d76671eb9b22679c9c1fc3dfcab51
    environment:
      - SWAGGER_JSON_URL=/specs/identigraf-uploader.yaml
      - BASE_URL=/swagger
      - DISPLAY_REQUEST_DURATION=true
      - DEFAULT_MODELS_EXPAND_DEPTH=100
      - DEFAULT_MODEL_EXPAND_DEPTH=100
      - DEEP_LINKING=true
      - VALIDATOR_URL=none

volumes:
  uploads:
