services:
  identigraf-uploader:
    build:
      context: .docker/identigraf-uploader
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - NO_UPDATE_NOTIFIER=true
      - NPM_CONFIG_FUND=0
      - SUPPRESS_SUPPORT=1
      - HTTPS=0
      - PORT=3000
      - ENABLE_TRACING=1
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - IDENTIGRAF_UPLOAD_FOLDER=/var/lib/identigraf-uploader/uploads
      - IDENTIGRAF_MAX_FILE_SIZE=5242880
      - HAVE_SWAGGER=true
      - npm_config_userconfig=/usr/src/service/.npmrc.local
    restart: always
    volumes:
      - "../:/usr/src/service"
      - uploads:/var/lib/identigraf-uploader/uploads
    working_dir: /usr/src/service

  zipkin:
    image: openzipkin/zipkin:latest@sha256:bb570eb45c2994eaf32da783cc098b3d51d1095b73ec92919863d73d0a9eaafb
    restart: always

  swagger:
    image: swaggerapi/swagger-ui:latest@sha256:9c2688be89e275bbc80b85ffedf52883233cbd1ec4636faff3eb618b6420acf2
    environment:
      - SWAGGER_JSON_URL=/specs/identigraf-uploader.yaml
      - BASE_URL=/swagger
      - DISPLAY_REQUEST_DURATION=true
      - DEFAULT_MODELS_EXPAND_DEPTH=100
      - DEFAULT_MODEL_EXPAND_DEPTH=100
      - DEEP_LINKING=true
      - VALIDATOR_URL=none

volumes:
  uploads:
